// Shared convention for the responsive image tiers generated by
// generate-image-variants.mjs: `{basename}-{width}w.webp`. content.json
// stores the 1200w path as the canonical/fallback reference; these helpers
// derive the other tiers' sibling filenames from it.

const TIER_SUFFIX = /-\d+w\.webp$/;

const stripTier = (path) => path.replace(TIER_SUFFIX, '');

export const buildSrc = (path, width) => `${stripTier(path)}-${width}w.webp`;

export const buildSrcSet = (path, widths) => {
    const base = stripTier(path);
    return widths.map((w) => `${base}-${w}w.webp ${w}w`).join(', ');
};
